### ISSUE TITLE
Removing page numbers (history counts)

### ISSUE THREAD

**Issue by su-stephen** [pjeby/pane-relief#13]
Is there a way to remove the number of pages in history? Ie the number that shows up near the forward and backward arrows for pane history. Thanks!

**Comment by pjeby** [comment]
Using a CSS snippet like this should do the job:

```css
.titlebar .history-counter { display: none; }
```
