### ISSUE TITLE
Navigation Buttons Broken with Obsidian v16.0

### ISSUE THREAD

**Issue by aidan-gibson** [pjeby/pane-relief#29]
With Pane Relief Enabled:
<img width="406" alt="Screen Shot 2022-08-29 at 23 51 42" src="https://user-images.githubusercontent.com/20917687/187369551-d9ecac56-ac3b-4cbf-bf47-ad09566480d1.png">

With Pane Relief Disabled:
<img width="362" alt="Screen Shot 2022-08-29 at 23 51 56" src="https://user-images.githubusercontent.com/20917687/187369611-1cedc839-f387-4e23-ab05-154cffa3baff.png">

**Comment by pjeby** [comment]
Hm.  It looks like MacOS is using display: block on the new theme instead of display: flex.  Try this CSS snippet and see if it works (and doesn't break anything else):

```css
body.obsidian-themepocalypse .titlebar-button-container {
    display: flex;
}
```
